% Cities: city(Name, Type, Region, Climate).
city(colombo, urban, west, tropical).
city(galle, beach, south, tropical).
city(mirissa, beach, south, tropical).
city(hambantota, beach, south, tropical).
city(kandy, cultural, central, mild).
city(nuwara_eliya, hill_country, central, cool).
city(ella, hill_country, uva, mild).
city(anuradhapura, historical, north_central, dry).
city(sigiriya, historical, north_central, dry).
city(yala, national_park, southeast, tropical).
city(horton_plains, national_park, central, cool).
city(jaffna, urban, north, dry).
city(trincomalee, beach, east, tropical).
city(arugam_bay, beach, east, tropical).
city(polonnaruwa, historical, north_central, dry).
city(dambulla, historical, central, dry).
city(bentota, beach, west, tropical).
city(negombo, beach, west, tropical).
city(matara, urban, south, tropical).
city(badulla, hill_country, uva, mild).
