% Distances (approx, km) - undirected
distance(colombo, kandy, 115).
distance(kandy, nuwara_eliya, 77).
distance(nuwara_eliya, ella, 60).
distance(colombo, mirissa, 155).
distance(colombo, galle, 119).
distance(galle, mirissa, 36).
distance(ella, yala, 130).
distance(colombo, anuradhapura, 205).
distance(anuradhapura, sigiriya, 22).
distance(kandy, sigiriya, 90).
distance(kandy, horton_plains, 60).
distance(mirissa, matara, 12).
distance(matara, hambantota, 80).
distance(hambantota, yala, 60).
distance(colombo, negombo, 34).
distance(negombo, kandy, 100).
distance(kandy, dambulla, 72).
distance(dambulla, sigiriya, 17).
distance(sigiriya, polonnaruwa, 60).
distance(polonnaruwa, trincomalee, 107).
distance(kandy, badulla, 137).
distance(badulla, ella, 28).
distance(trincomalee, anuradhapura, 110).
distance(anuradhapura, jaffna, 200).
distance(arugam_bay, yala, 160).
distance(arugam_bay, ella, 165).
distance(bentota, galle, 56).
distance(bentota, colombo, 65).
